// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAf0iWw5lIb2_A3BBSo0TByH0YvtuZWIqY',
    appId: '1:1639155859:web:e35ac63a2d59162ffea566',
    messagingSenderId: '1639155859',
    projectId: 'flutter-app-2319b',
    authDomain: 'flutter-app-2319b.firebaseapp.com',
    storageBucket: 'flutter-app-2319b.appspot.com',
    measurementId: 'G-26SGG8XGZ5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCx3yYvmdaWc23oWYuV71Mt7tzX1LnBDwA',
    appId: '1:1639155859:android:11bfcd68670e7750fea566',
    messagingSenderId: '1639155859',
    projectId: 'flutter-app-2319b',
    storageBucket: 'flutter-app-2319b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDm8s1rXF3Y9-bWIrAS7Ya2iylO2osZknw',
    appId: '1:1639155859:ios:319451cffba12491fea566',
    messagingSenderId: '1639155859',
    projectId: 'flutter-app-2319b',
    storageBucket: 'flutter-app-2319b.appspot.com',
    iosClientId: '1639155859-ab7va3satv4nkufdvr7cv06814gitved.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixmeFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDm8s1rXF3Y9-bWIrAS7Ya2iylO2osZknw',
    appId: '1:1639155859:ios:c2abfb5d2e27248afea566',
    messagingSenderId: '1639155859',
    projectId: 'flutter-app-2319b',
    storageBucket: 'flutter-app-2319b.appspot.com',
    iosClientId: '1639155859-jla0mpl29qtk2bjeg8gc7sd59h2km8l8.apps.googleusercontent.com',
    iosBundleId: 'com.example.fixmeFlutter.RunnerTests',
  );
}
